spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2DB
    username: sa
    password:
    driverClassName: org.h2.Driver